#!/bin/bash

set -e

work_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

unpack_dir="$1"

if [[ -z "$unpack_dir" || ! -d "$unpack_dir" ]]; then
    echo -e "${RED}ERROR: Direktori unpack '$unpack_dir' tidak valid.${NC}" >&2
    exit 1
fi

expressions_fix() {
    local var="$1"
    local escaped_var
    escaped_var=$(printf '%s\n' "$var" | sed 's/[\/&]/\\&/g')
    escaped_var=$(printf '%s\n' "$escaped_var" | sed 's/\[/\\[/g' | sed 's/\]/\\]/g' | sed 's/\./\\./g' | sed 's/;/\\;/g')
    echo "$escaped_var"
}

certificatechainPatch() {
 certificatechainPatch="
    .line $1
    invoke-static {}, Lcom/android/internal/util/danda/OemPorts10TUtils;->onEngineGetCertificateChain()V
"
}
instrumentationPatch() {
	local returnline=$(expr $2 + 1)
	instrumentationPatch="    invoke-static {$1}, Lcom/android/internal/util/danda/OemPorts10TUtils;->onNewApplication(Landroid/content/Context;)V
    
    .line $returnline
    "
}
blSpoofPatch() {
	blSpoofPatch="    invoke-static {$1}, Lcom/android/internal/util/danda/OemPorts10TUtils;->genCertificateChain([Ljava/security/cert/Certificate;)[Ljava/security/cert/Certificate;
	
    move-result-object $1
    "
}

keystorespiclassfile=$(find "$unpack_dir"/ -name 'AndroidKeyStoreSpi.smali' -printf '%P\n' | head -n 1)
instrumentationsmali=$(find "$unpack_dir"/ -name "Instrumentation.smali" -printf '%P\n' | head -n 1)

if [[ -z "$keystorespiclassfile" || -z "$instrumentationsmali" ]]; then
    echo -e "${RED}    ERROR: PIF patch failed. Required files not found (KStoreSpi/Inst).${NC}" >&2
    exit 1
fi

local_keystore_path="$unpack_dir/$keystorespiclassfile"
local_inst_path="$unpack_dir/$instrumentationsmali"
engineGetCertMethod=$(expressions_fix "$(grep 'engineGetCertificateChain(' "$local_keystore_path")")
newAppMethod1=$(expressions_fix "$(grep 'newApplication(Ljava/lang/ClassLoader;' "$local_inst_path")")
newAppMethod2=$(expressions_fix "$(grep 'newApplication(Ljava/lang/Class;' "$local_inst_path")")

sed -n "/^${engineGetCertMethod}/,/^\.end method/p" "$local_keystore_path" > "$work_dir/tmp_keystore"
sed -i "/^${engineGetCertMethod}/,/^\.end method/d" "$local_keystore_path"
sed -n "/^${newAppMethod1}/,/^\.end method/p" "$local_inst_path" > "$work_dir/inst1"
sed -i "/^${newAppMethod1}/,/^\.end method/d" "$local_inst_path"
sed -n "/^${newAppMethod2}/,/^\.end method/p" "$local_inst_path" > "$work_dir/inst2"
sed -i "/^${newAppMethod2}/,/^\.end method/d" "$local_inst_path"

inst1_insert=$(expr $(wc -l < "$work_dir/inst1") - 2)
instreg=$(grep "Landroid/app/Application;->attach(Landroid/content/Context;)V" "$work_dir/inst1" | awk '{print $3}' | sed 's/},//')
instline=$(expr $(grep -r ".line" "$work_dir/inst1" | tail -n 1 | awk '{print $2}') + 1)
instrumentationPatch "$instreg" "$instline"
echo "$instrumentationPatch" | sed -i "${inst1_insert}r /dev/stdin" "$work_dir/inst1"

inst2_insert=$(expr $(wc -l < "$work_dir/inst2") - 2)
instreg=$(grep "Landroid/app/Application;->attach(Landroid/content/Context;)V" "$work_dir/inst2" | awk '{print $3}' | sed 's/},//')
instline=$(expr $(grep -r ".line" "$work_dir/inst2" | tail -n 1 | awk '{print $2}') + 1)
instrumentationPatch "$instreg" "$instline"
echo "$instrumentationPatch" | sed -i "${inst2_insert}r /dev/stdin" "$work_dir/inst2"

kstoreline=$(expr $(grep -r ".line" "$work_dir/tmp_keystore" | head -n 1 | awk '{print $2}') - 2)
certificatechainPatch "$kstoreline"
echo "$certificatechainPatch" | sed -i '4r /dev/stdin' "$work_dir/tmp_keystore"

lastaput=$(grep "aput-object" "$work_dir/tmp_keystore" | tail -n 1)
leafcert=$(echo "$lastaput" | awk '{print $3}' | awk -F',' '{print $1}')
blspoof_insert=$(expr $(grep -n "$lastaput" "$work_dir/tmp_keystore" | awk -F':' '{print $1}') + 1)
blSpoofPatch "$leafcert"
echo "$blSpoofPatch" | sed -i "${blspoof_insert}r /dev/stdin" "$work_dir/tmp_keystore"

cat "$work_dir/inst1" >> "$local_inst_path"
cat "$work_dir/inst2" >> "$local_inst_path"
cat "$work_dir/tmp_keystore" >> "$local_keystore_path"
rm -rf "$work_dir/inst1" "$work_dir/inst2" "$work_dir/tmp_keystore"
exit 0